name: epub
version: 2.1.1
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  async: ">=1.8.0 <3.0.0"
  archive: ^4.0.3
  quiver: ^3.2.2
  xml: ^6.5.0
  image: ^4.5.3
dev_dependencies:
  test: ^1.21.1
  path: ^1.8.1
  lints: ^5.1.1
