name: epub
version: 2.1.1
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  async: ">=1.8.0 <3.0.0"
  archive: ^3.3.0
  quiver: ^3.1.0
  xml: ^5.4.1
  image: ^3.1.3
dev_dependencies:
  test: ^1.21.1
  path: ^1.8.1
  lints: ^2.0.0
